### PR TITLE
Updates project to settings recommended by Xcode 9.2

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by divo** [comment]
@valeriyvan thanks for the contribution, https://github.com/zendesk/Suas-iOS/pull/31 solves this.

**Comment by valeriyvan** [comment]
PRs hang not reviews for months.
Then you do same changes yourself.
Why?

**Comment by divo** [comment]
@valeriyvan we are getting ready for a release which uses Suas, I went through and cherry-picked the most recent changes someone else had made.

We don't have the resources to continually update Suas as pull requests come in.

**Comment by valeriyvan** [comment]
From README:
> We love any sort of contribution. From changing the internals of how Suas works, changing Suas methods and public API, changing readmes and documentation topics.

**Pull request closed without merging**
