### PR TITLE
Refactors forEach for using trailing block syntax

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by valeriyvan** [comment]
Ping @divo
Are contributions welcome to this repo?

**Comment by divo** [comment]
@valeriyvan We are very busy at the moment trying to get a release together. I will look at your refactoring PRs after this is done.

**Comment by bielikb** [comment]
Hey @valeriyvan, thanks for all your contributions to this repo.
Could you please update your PRs? Thanks!

**Comment by valeriyvan** [comment]
Hi, @bielikb.
I have updated my PRs.

**Comment by bielikb** [comment]
Thanks @valeriyvan!

**Comment by valeriyvan** [comment]
Only 22 month were needed to merge this PR. 
PRs #22 and #32 are still waiting.

**Pull request merged**
